### ISSUE TITLE
field_widget_form missing?

### ISSUE THREAD

**Issue by mansxu** [signalpoint/addressfield#1]
I installed the module and the display of addresses in the user settings is fine, but editing gives me an error. Following the debugging trail, it appears that the addressfield_field_widget_form function is missing in the module. Is that intentional? Or did you just not get around to implementing it?

**Comment by signalpoint** [comment]
@mansxu Thanks for reporting this. As it stands, I haven't got around to implementing it yet (aka no client's have needed it yet). It shouldn't be too difficult to accomplish though, please consider contributing to make it happen ;)

www.drupalgap.org/node/216

http://www.drupalgap.org/contribute

**Comment by signalpoint** [comment]
@mansxu This feature was added a while ago (probably one or more years ago), I forgot to close out this issue though.
